# Generated by Django 5.0.2 on 2024-03-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ifood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumidor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
